server:
  port: 0

spring:
  application:
    name: ordering-service

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException
    instances:
      userService:
        base-config: default
        sliding-window-size: 10
      productService:
        base-config: default
        sliding-window-size: 30
      productServiceUpdate:
        base-config: default
        sliding-window-size: 5
        failure-rate-threshold: 30
        wait-duration-in-open-state: 5000


  timelimiter:
    configs:
      default:
        timeout-duration: 3s
        cancel-running-future: true
    instances:
      userService:
        base-config: default
      productService:
        base-config: default
        timeout-duration: 1s
      productServiceUpdate:
        base-config: default
        timeout-duration: 1s
  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 1s
      productService:
        max-attempts: 5
        wait-duration: 2s
      productServiceUpdate:
        max-attempts: 3
        wait-duration: 1s





