server:
  port: 0

spring:
  application:
    name: user-service

  # 카카오 로그인용 데이터
oauth2:
  kakao:
    client-id: ba98e521fbb271a7148646b621c80c92
    redirect-uri: http://localhost:8000/user-service/user/kakao












